-- 코드를 입력하세요
SELECT REST_INFO.REST_ID as REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, round(avg(REVIEW_SCORE),2) as SCORE
FROM REST_INFO, REST_REVIEW
WHERE REST_INFO.REST_ID = REST_REVIEW.REST_ID
GROUP BY REST_INFO.REST_ID having ADDRESS like "서울%"
ORDER BY SCORE desc, FAVORITES desc